<?php
require_once("checkSession.php");
require_once("top.php");
require_once("connection.php");

$delete = $_POST["chkDelete"];

if (isset($delete)) {
	for ($i = 0; $i < count($delete); $i++) {
		$queryAssetDel = mysqli_query($connection, "delete " . $dbAssetArray["ASSET_TABLE"] . ", " . $dbFirmwareArray["FIRMWARE_TABLE"] . ", " . $dbHardwareArray["HARDWARE_TABLE"] . ", " . $dbProcessorArray["PROCESSOR_TABLE"] . ", " . $dbRamArray["RAM_TABLE"] . ", " . $dbStorageArray["STORAGE_TABLE"] . ", " . $dbVideoCardArray["VIDEO_CARD_TABLE"] . ", " . $dbLocationArray["LOCATION_TABLE"] . ", " . $dbMaintenanceArray["MAINTENANCE_TABLE"] . ", " . $dbNetworkArray["NETWORK_TABLE"] . ", " . $dbOperatingSystemArray["OPERATING_SYSTEM_TABLE"] . " from " . $dbAssetArray["ASSET_TABLE"] . " inner join " . $dbFirmwareArray["FIRMWARE_TABLE"] . " inner join " . $dbHardwareArray["HARDWARE_TABLE"] . " inner join " . $dbProcessorArray["PROCESSOR_TABLE"] . " inner join " . $dbRamArray["RAM_TABLE"] . " inner join " . $dbStorageArray["STORAGE_TABLE"] . " inner join " . $dbVideoCardArray["VIDEO_CARD_TABLE"] . " inner join " . $dbLocationArray["LOCATION_TABLE"] . " inner join " . $dbMaintenanceArray["MAINTENANCE_TABLE"] . " inner join " . $dbNetworkArray["NETWORK_TABLE"] . " inner join " . $dbOperatingSystemArray["OPERATING_SYSTEM_TABLE"] . " on " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbFirmwareArray["FIRMWARE_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbHardwareArray["HARDWARE_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbProcessorArray["PROCESSOR_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbRamArray["RAM_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbStorageArray["STORAGE_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbVideoCardArray["VIDEO_CARD_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbLocationArray["LOCATION_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbMaintenanceArray["MAINTENANCE_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbNetworkArray["NETWORK_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " AND " . $dbAssetArray["ASSET_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER"] . " = " . $dbOperatingSystemArray["OPERATING_SYSTEM_TABLE"] . "." . $dbAssetArray["ASSET_NUMBER_FK"] . " where " . $dbAssetArray["ASSET_TABLE"] . ".id = '$delete[$i]'") or die($translations["ERROR_DELETE_ASSET"] . mysqli_error($connection));
	}
}

header("Location: queryAsset.php?del=ok");
