-- MySQL Script generated by MySQL Workbench
-- Sat Jun  5 15:13:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema patrimonio
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema patrimonio
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `patrimonio` DEFAULT CHARACTER SET utf8 ;
USE `patrimonio` ;

-- -----------------------------------------------------
-- Table `patrimonio`.`bios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patrimonio`.`bios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NULL DEFAULT NULL,
  `modelo` VARCHAR(45) NULL DEFAULT NULL,
  `versao` VARCHAR(45) NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 102
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `patrimonio`.`docente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patrimonio`.`docente` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `siape` VARCHAR(45) NULL DEFAULT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `ramal` VARCHAR(45) NULL DEFAULT NULL,
  `celular` VARCHAR(45) NULL DEFAULT NULL,
  `curso` VARCHAR(45) NULL DEFAULT NULL,
  `sala` VARCHAR(45) NULL DEFAULT NULL,
  `faltas` INT(2) NULL DEFAULT '0',
  `data_ultima_falta` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 403
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `patrimonio`.`manutencoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patrimonio`.`manutencoes` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `patrimonioFK` INT(11) NULL DEFAULT NULL,
  `dataFormatacoesAnteriores` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 514
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `patrimonio`.`patrimonio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patrimonio`.`patrimonio` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `patrimonio` INT(11) NULL DEFAULT NULL,
  `predio` VARCHAR(20) NULL DEFAULT NULL,
  `sala` VARCHAR(10) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `nomeRecebedor` VARCHAR(50) NULL DEFAULT NULL,
  `siapeRecebedor` VARCHAR(50) NULL DEFAULT NULL,
  `ramal` VARCHAR(15) NULL DEFAULT NULL,
  `dataEntrega` VARCHAR(10) NULL DEFAULT NULL,
  `observacao` TEXT NULL DEFAULT NULL,
  `padrao` VARCHAR(10) NULL DEFAULT 'SIM',
  `dataFormatacao` VARCHAR(10) NULL DEFAULT NULL,
  `ad` VARCHAR(5) NULL DEFAULT NULL,
  `marca` VARCHAR(30) NULL DEFAULT NULL,
  `modelo` VARCHAR(50) NULL DEFAULT NULL,
  `numSerie` VARCHAR(50) NULL DEFAULT NULL,
  `processador` VARCHAR(75) NULL DEFAULT NULL,
  `memoria` VARCHAR(30) NULL DEFAULT NULL,
  `hd` VARCHAR(30) NULL DEFAULT NULL,
  `idUsuario` INT(11) NULL DEFAULT NULL,
  `sistemaOperacional` VARCHAR(70) NULL DEFAULT NULL,
  `hostname` VARCHAR(30) NULL DEFAULT NULL,
  `emUso` VARCHAR(10) NULL DEFAULT NULL,
  `lacre` VARCHAR(30) NULL DEFAULT NULL,
  `etiqueta` VARCHAR(10) NULL DEFAULT NULL,
  `mac` VARCHAR(30) NULL DEFAULT NULL,
  `ip` VARCHAR(30) NULL DEFAULT NULL,
  `tipo` VARCHAR(10) NULL DEFAULT NULL,
  `bios` VARCHAR(40) NULL DEFAULT NULL,
  `tipoFW` VARCHAR(10) NULL DEFAULT NULL,
  `tipoArmaz` VARCHAR(45) NULL DEFAULT NULL,
  `gpu` VARCHAR(45) NULL DEFAULT NULL,
  `modoArmaz` VARCHAR(45) NULL DEFAULT NULL,
  `secBoot` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 1606
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `patrimonio`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `patrimonio`.`usuarios` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NULL DEFAULT NULL,
  `senha` VARCHAR(50) NULL DEFAULT NULL,
  `nivel` VARCHAR(5) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT '0',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 25
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
